language: java
deploy:
  provider: heroku
  on: ajax-book-reviews
  api_key:
    secure: tQO+3j9cUz21HyBojiMnG7aWcGOM7Z40W+dD27Dn0FzMsSujzfUCRUNKcUI62xLNQShvwDY2FeLelMXyX19q1kyxrk+mc9syPydiYPMVD3gczKevHqh9ESYJsxZADrJk8zXTPyQFgqtucZQpvegb9GKxUchS26mGIBAc4F9PUlEIn6sYIf3bpnWilhU58Ot8w8sI+nBavsTwQFoDx6ih9xm7iBhuQSf8fYr3YOJiYDk9ZTq0Pj3NPxkLa6sn2F2FDbX4qQ7wnZDFw2oZnFPz0CilRgpMCeSF+f/KkTCCQUJMTJTpKejk5olvP1fJApx+VPloNJC7TXNYQ9+L0IvC0DC+azkt/nqsy66lhCouJ+SrY9UkPmNw16CKckeJsHseVv+08geA+hBm6z1Y1arHVCizlI+iaH59KhDDIWbBgJKKfaV+SX9zOdEmzNfPxKML7eWBEH09UlP4V4G0zc6wBuU6FgMmTuyIQzphBJW/gukWTcniq8eEUN229reIgBjZkvUfQMpSbQHRcg0MXdana8Lb9XlgL7uYZvvFmBjBvVJ1+4Ej1LaZErfr/uXq7xf48qLy8i5hSMEkS/DZt31DewM1P22n/Ujr4Cab93yAQYBc6GU3VYIze5x/KQgDZmG5G6ZIbmUXX4c/TWIK8Cfv0+n1xII1HyVKpLkZqEVFiOk=
